### ISSUE TITLE
Swift Compile Errors? 

### ISSUE THREAD

**Issue by harperAtustwo** [cgreening/VisionCoreMLSample#5]
Hi as you can see by the attachment, I am getting the following errors. Any clue? 
![screen shot 2017-07-20 at 15 47 18](https://user-images.githubusercontent.com/23457841/28435891-e4c80666-6d62-11e7-88cf-e9cbf891a941.png)

**Comment by cgreening** [comment]
Make sure you are using beta 3 of Xcode.

<img width="532" alt="screen shot 2017-07-21 at 21 18 40" src="https://user-images.githubusercontent.com/706944/28480792-41f64b2a-6e5a-11e7-8cb9-3acde547e29f.png">
